version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_DATABASE: secure_keeper_data
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -p$$MYSQL_ROOT_PASSWORD | grep 'alive'" ]
      interval: 5s
      timeout: 10s
      retries: 10

  app:
    build: .
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/secure_keeper_data
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "123"
      SERVER_PORT: "8090"
    depends_on:
      mysql_db:
        condition: service_healthy

volumes:
  mysql_data: